name: Test

on:
  push:
  pull_request:
    types: [review_requested]
  workflow_dispatch:

jobs:
  test:
    name: TestBench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install iverilog and gtkwave
        run: sudo -E apt-get -y install iverilog gtkwave
      - name: Run TestBench
        run: make
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Upload simulation results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: simulation-results
          path: |
            !**/node_modules/**
            **/*.vvp
            **/*.vcd
            **/*.out
          retention-days: 7
