name: Test

on:
  push:
  pull_request: [review_requested]
  workflow_dispatch:

jobs:
  test:
    name: TestBench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install iverilog and gtkwave
        run: sudo -E apt-get -y install iverilog gtkwave
      - name: Run TestBench
        run: |
          sed -i 's/^VVP_FLAGS :=/# VVP_FLAGS :=/' Makefile
          make
